[package]
name = "qk-cli"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "qk"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
ctrlc.workspace = true
qk-config.workspace = true
qk-graph.workspace = true
qk-taskgraph.workspace = true
qk-runner.workspace = true
qk-executor.workspace = true
qk-cache.workspace = true
qk-affected.workspace = true
qk-history.workspace = true
qk-lockfile.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
